version: '3.7'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2
    container_name: opensearch-node1
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Vardan@20072004
    volumes:
      - C:/Users/U_M22DE/PycharmProjects/OS/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
     # - C:/Users/U_M22DE/PycharmProjects/OS/opensearch/config/opensearch-security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - mynetwork

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: dashboards
    volumes:
      - C:\Users\U_M22DE\PycharmProjects\OS\opensearch_dashboard\opensearch_dashboard.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - 5601:5601
    networks:
      - mynetwork

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/logstash.conf:ro
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - mynetwork
    depends_on:
      - opensearch-node1

  metricbeat:
    image: elastic/metricbeat:8.7.1
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock  #для конта будет
    command: >
      sh -c "chmod go-w /usr/share/metricbeat/metricbeat.yml && 
              metricbeat -e -c /usr/share/metricbeat/metricbeat.yml"
    depends_on:
      - opensearch-node1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge