version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch-node1
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Vardan@2004
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - C:\Users\вард\PycharmProjects\OS\opensearch\opensearch.yml:/usr/share/opensearch/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600
 #   networks:
  #    - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    volumes:
      - C:\Users\вард\PycharmProjects\OS\opensearch_dashboard\opensearch_dashboard.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboard.yml
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
 #   networks:
 #     - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/logstash.conf:ro
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
##    networks:
 #     - opensearch-net
    depends_on:
      - opensearch-node1

  metricbeat:
    image: elastic/metricbeat:8.7.1
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock  #для конта будет
    command: >
      sh -c "chmod go-w /usr/share/metricbeat/metricbeat.yml && 
              metricbeat -e -c /usr/share/metricbeat/metricbeat.yml"
    depends_on:
      - opensearch-node1
  #  networks:
  #    - opensearch-net

volumes:
  opensearch-data1:

#networks:
#  opensearch-net:
